#!/bin/bash

rm out_sparsification/uniform_int/*theta6*
rm out_sparsification/uniform_int/*theta8*
rm out_sparsification/uniform_int/*theta10*
rm out_sparsification/uniform_int/*theta12*
rm out_sparsification/uniform_int/*theta14*
rm out_sparsification/uniform_int/*theta16*
rm out_sparsification/uniform_int/*theta18*
rm out_sparsification/uniform_int/*theta20*
rm out_sparsification/uniform_int/*theta22*
rm out_sparsification/uniform_int/*theta24*

rm out_sparsification/uniform_int/*yao6*
rm out_sparsification/uniform_int/*yao8*
rm out_sparsification/uniform_int/*yao10*
rm out_sparsification/uniform_int/*yao12*
rm out_sparsification/uniform_int/*yao14*
rm out_sparsification/uniform_int/*yao16*
rm out_sparsification/uniform_int/*yao18*
rm out_sparsification/uniform_int/*yao20*
rm out_sparsification/uniform_int/*yao22*
rm out_sparsification/uniform_int/*yao24*

rm out_sparsification/uniform_real/*theta6*
rm out_sparsification/uniform_real/*theta8*
rm out_sparsification/uniform_real/*theta10*
rm out_sparsification/uniform_real/*theta12*
rm out_sparsification/uniform_real/*theta14*
rm out_sparsification/uniform_real/*theta16*
rm out_sparsification/uniform_real/*theta18*
rm out_sparsification/uniform_real/*theta20*
rm out_sparsification/uniform_real/*theta22*
rm out_sparsification/uniform_real/*theta24*

rm out_sparsification/uniform_real/*yao6*
rm out_sparsification/uniform_real/*yao8*
rm out_sparsification/uniform_real/*yao10*
rm out_sparsification/uniform_real/*yao12*
rm out_sparsification/uniform_real/*yao14*
rm out_sparsification/uniform_real/*yao16*
rm out_sparsification/uniform_real/*yao18*
rm out_sparsification/uniform_real/*yao20*
rm out_sparsification/uniform_real/*yao22*
rm out_sparsification/uniform_real/*yao24*

rm out_sparsification/normal/*theta6*
rm out_sparsification/normal/*theta8*
rm out_sparsification/normal/*theta10*
rm out_sparsification/normal/*theta12*
rm out_sparsification/normal/*theta14*
rm out_sparsification/normal/*theta16*
rm out_sparsification/normal/*theta18*
rm out_sparsification/normal/*theta20*
rm out_sparsification/normal/*theta22*
rm out_sparsification/normal/*theta24*

rm out_sparsification/normal/*yao6*
rm out_sparsification/normal/*yao8*
rm out_sparsification/normal/*yao10*
rm out_sparsification/normal/*yao12*
rm out_sparsification/normal/*yao14*
rm out_sparsification/normal/*yao16*
rm out_sparsification/normal/*yao18*
rm out_sparsification/normal/*yao20*
rm out_sparsification/normal/*yao22*
rm out_sparsification/normal/*yao24*

rm out_sparsification/uniform_int/*wspd2*
rm out_sparsification/uniform_int/*wspd3*
rm out_sparsification/uniform_int/*wspd4*
rm out_sparsification/uniform_int/*wspd5*
rm out_sparsification/uniform_int/*wspd6*
rm out_sparsification/uniform_int/*wspd7*
rm out_sparsification/uniform_int/*wspd0-1*
rm out_sparsification/uniform_int/*wspd0-2*
rm out_sparsification/uniform_int/*wspd0-3*
rm out_sparsification/uniform_int/*wspd0-4*
rm out_sparsification/uniform_int/*onion-0*
rm out_sparsification/uniform_int/*onion-1*
rm out_sparsification/uniform_int/*onion-2*
rm out_sparsification/uniform_int/*greedy2*

rm out_sparsification/uniform_real/*wspd2*
rm out_sparsification/uniform_real/*wspd3*
rm out_sparsification/uniform_real/*wspd4*
rm out_sparsification/uniform_real/*wspd5*
rm out_sparsification/uniform_real/*wspd6*
rm out_sparsification/uniform_real/*wspd7*
rm out_sparsification/uniform_real/*wspd0-1*
rm out_sparsification/uniform_real/*wspd0-2*
rm out_sparsification/uniform_real/*wspd0-3*
rm out_sparsification/uniform_real/*wspd0-4*
rm out_sparsification/uniform_real/*onion-0*
rm out_sparsification/uniform_real/*onion-1*
rm out_sparsification/uniform_real/*onion-2*
rm out_sparsification/uniform_real/*greedy2*

rm out_sparsification/normal/*wspd2*
rm out_sparsification/normal/*wspd3*
rm out_sparsification/normal/*wspd4*
rm out_sparsification/normal/*wspd5*
rm out_sparsification/normal/*wspd6*
rm out_sparsification/normal/*wspd7*
rm out_sparsification/normal/*wspd0-1*
rm out_sparsification/normal/*wspd0-2*
rm out_sparsification/normal/*wspd0-3*
rm out_sparsification/normal/*wspd0-4*
rm out_sparsification/normal/*onion-0*
rm out_sparsification/normal/*onion-1*
rm out_sparsification/normal/*onion-2*
rm out_sparsification/normal/*greedy2*
